"""empty message

Revision ID: 1330a2d0219b
Revises: 85f338319e61
Create Date: 2022-07-25 22:33:21.871783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1330a2d0219b'
down_revision = '85f338319e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_usuario_fk', sa.Integer(), nullable=True),
    sa.Column('id_mesa_fk', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mesa_fk'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_usuario_fk'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_reserva')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    # ### end Alembic commands ###
