"""empty message

Revision ID: 85f338319e61
Revises: efa9fa0c4f87
Create Date: 2022-07-25 22:31:43.611144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85f338319e61'
down_revision = 'efa9fa0c4f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserva', 'id_usuario_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('reserva', 'id_mesa_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserva', 'id_mesa_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('reserva', 'id_usuario_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
