"""empty message

Revision ID: c65bc9e1bcb8
Revises: 4099d47a2b6a
Create Date: 2022-07-25 22:24:21.685119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65bc9e1bcb8'
down_revision = '4099d47a2b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_mesa')
    )
    op.create_table('reserva',
    sa.Column('id_usuario_fk', sa.Integer(), nullable=False),
    sa.Column('id_mesa_fk', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_mesa_fk'], ['mesa.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_usuario_fk'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_fk', 'id_mesa_fk')
    )
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.drop_table('reserva')
    op.drop_table('mesa')
    # ### end Alembic commands ###
