"""empty message

Revision ID: efa9fa0c4f87
Revises: c65bc9e1bcb8
Create Date: 2022-07-25 22:30:11.499647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efa9fa0c4f87'
down_revision = 'c65bc9e1bcb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva', sa.Column('id_reserva', sa.Integer(), nullable=False))
    op.alter_column('reserva', 'id_usuario_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('reserva', 'id_mesa_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reserva', 'id_mesa_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('reserva', 'id_usuario_fk',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('reserva', 'id_reserva')
    # ### end Alembic commands ###
